<a href="https://colab.research.google.com/github/JoaquinGonzalezSimon/Data_science_and_ML_from_Medium/blob/main/220904_Netflix_Data_Analysis_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### This project was taken from the following link and I use it to practice my skills

https://thecleverprogrammer.com/2021/01/16/netflix-data-analysis-with-python/

https://medium.com/coders-camp/180-data-science-and-machine-learning-projects-with-python-6191bc7b9db9

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np
import plotly.express as px
from textblob import TextBlob

In [3]:
data = pd.read_csv('/content/drive/MyDrive/Ironhack/DBs/netflix_titles.csv')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [5]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [6]:
data.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [7]:
data.shape

(8807, 12)

In [11]:
z = data.groupby('rating').size().reset_index(name='counts')
pieChart = px.pie(z, values='counts', names='rating', title='Distribution of content ratings on Netflix',
                  color_discrete_sequence=px.colors.qualitative.Set3)
pieChart.show()

In [17]:
data['director'] = data['director'].fillna('No Director Specified')
filtered_directors = pd.DataFrame()
filtered_directors = data['director'].str.split(', ', expand=True).stack()

In [20]:
filtered_directors = filtered_directors.to_frame()

In [22]:
filtered_directors.columns=['Director']
filtered_directors

                     Director
0    0        Kirsten Johnson
1    0  No Director Specified
2    0        Julien Leclercq
3    0  No Director Specified
4    0  No Director Specified
...                       ...
8802 0          David Fincher
8803 0  No Director Specified
8804 0        Ruben Fleischer
8805 0           Peter Hewitt
8806 0            Mozez Singh

[9612 rows x 1 columns]

In [28]:
 directors = filtered_directors.groupby('Director').size().reset_index(name='Total content')
 directors

                 Director  Total content
0             A. L. Vijay              2
1            A. Raajdheep              1
2               A. Salaam              1
3         A.R. Murugadoss              2
4         Aadish Keluskar              1
...                   ...            ...
4989           Éric Warin              1
4990     Ísold Uggadóttir              1
4991  Óskar Thór Axelsson              1
4992     Ömer Faruk Sorak              3
4993         Şenol Sönmez              2

[4994 rows x 2 columns]

In [33]:
directors = directors[directors.Director != 'No Director Specified']

In [34]:
directors = directors.sort_values(by=['Total content'], ascending=False)
directors

                     Director  Total content
3750            Rajiv Chilaka             22
1906                Jan Suter             21
3801              Raúl Campos             19
4458              Suhas Kadav             16
2866             Marcus Raboy             16
...                       ...            ...
635              Brandon Camp              1
2295               Juan Antin              1
2296  Juan Antonio de la Riva              1
2297       Juan Camilo Pinzon              1
2957        María Jose Cuevas              1

[4993 rows x 2 columns]

In [35]:
directorsTop5 = directors.head()

In [40]:
directorsTop5 = directorsTop5.sort_values('Total content', ascending=True)

In [41]:
fig1 = px.bar(directorsTop5, x='Total content', y='Director', title='Top 5 Directors in Netflix')
fig1.show()

In [42]:
data['cast'] = data['cast'].fillna('No Cast Specified')
data['cast'].value_counts()

No Cast Specified                                                                                                                                                                             825
David Attenborough                                                                                                                                                                             19
Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jigna Bhardwaj, Rajesh Kava, Mousam, Swapnil                                                                                                        14
Samuel West                                                                                                                                                                                    10
Jeff Dunham                                                                                                                                                                                     7
                                                                                                                                                                                             ...
Nick Lachey, Vanessa Lachey                                                                                                                                                                     1
Takeru Sato, Kasumi Arimura, Haru, Kentaro Sakaguchi, Takayuki Yamada, Kendo Kobayashi, Ken Yasuda, Arata Furuta, Suzuki Matsuo, Koichi Yamadera, Arata Iura, Chikako Kaku, Kotaro Yoshida      1
Toyin Abraham, Sambasa Nzeribe, Chioma Chukwuka Akpotha, Chioma Omeruah, Chiwetalu Agu, Dele Odule, Femi Adebayo, Bayray McNwizu, Biodun Stephen                                                1
Neeraj Kabi, Geetanjali Kulkarni, Danish Husain, Sheeba Chaddha, Paras Priyadarshan, Anshul Chauhan, Anud Singh Dhaka, Shirin Sewani, Mihir Ahuja, Vasundhara Rajput                            1
Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanana, Manish Chaudhary, Meghna Malik, Malkeet Rauni, Anita Shabdish, Chittaranjan Tripathy                                                           1
Name: cast, Length: 7693, dtype: int64

In [47]:
filtered_cast = pd.DataFrame(data['cast'].str.split(',', expand=True).stack())
filtered_cast

                             0
0    0       No Cast Specified
1    0              Ama Qamata
     1             Khosi Ngema
     2           Gail Mabalane
     3          Thabang Molaba
...                        ...
8806 3        Manish Chaudhary
     4            Meghna Malik
     5           Malkeet Rauni
     6          Anita Shabdish
     7   Chittaranjan Tripathy

[64951 rows x 1 columns]

In [48]:
filtered_cast.columns=['Actors']
filtered_cast.head()

                Actors
0 0  No Cast Specified
1 0         Ama Qamata
  1        Khosi Ngema
  2      Gail Mabalane
  3     Thabang Molaba

In [52]:
actors = filtered_cast.groupby('Actors').size().reset_index(name='Total Content').sort_values(by='Total Content', ascending=False)
actors

                   Actors  Total Content
37649   No Cast Specified            825
2612          Anupam Kher             39
26941        Rupa Bhimani             31
30303    Takahiro Sakurai             30
15541       Julie Tejwani             28
...                   ...            ...
15291   João Fábio Cabral              1
15290         João Côrtes              1
15289       João Assunção              1
15288      Joziah Lagonoy              1
39296        Ṣọpẹ́ Dìrísù              1

[39297 rows x 2 columns]

In [54]:
actors = actors[actors.Actors != 'No Cast Specified']
actors

                   Actors  Total Content
2612          Anupam Kher             39
26941        Rupa Bhimani             31
30303    Takahiro Sakurai             30
15541       Julie Tejwani             28
23624             Om Puri             27
...                   ...            ...
15291   João Fábio Cabral              1
15290         João Côrtes              1
15289       João Assunção              1
15288      Joziah Lagonoy              1
39296        Ṣọpẹ́ Dìrísù              1

[39296 rows x 2 columns]

In [57]:
fig2 = px.bar(actors.head().sort_values(by='Total Content', ascending=True), x='Total Content', y='Actors', title='Top 5 Actors on Netflix')
fig2.show()

In [58]:
data.isnull().sum()

show_id           0
type              0
title             0
director          0
cast              0
country         831
date_added       10
release_year      0
rating            4
duration          3
listed_in         0
description       0
dtype: int64

In [60]:
df1 = data[['type', 'release_year']]
df1

         type  release_year
0       Movie          2020
1     TV Show          2021
2     TV Show          2021
3     TV Show          2021
4     TV Show          2021
...       ...           ...
8802    Movie          2007
8803  TV Show          2018
8804    Movie          2009
8805    Movie          2006
8806    Movie          2015

[8807 rows x 2 columns]

In [63]:
df2 = df1.groupby(['release_year', 'type']).size().reset_index(name='Total Contents')
df2

     release_year     type  Total Contents
0            1925  TV Show               1
1            1942    Movie               2
2            1943    Movie               3
3            1944    Movie               3
4            1945    Movie               3
..            ...      ...             ...
114          2019  TV Show             397
115          2020    Movie             517
116          2020  TV Show             436
117          2021    Movie             277
118          2021  TV Show             315

[119 rows x 3 columns]

In [64]:
df3 = df2[df2.release_year >= 1990]
df3

     release_year     type  Total Contents
55           1990    Movie              19
56           1990  TV Show               3
57           1991    Movie              16
58           1991  TV Show               1
59           1992    Movie              20
..            ...      ...             ...
114          2019  TV Show             397
115          2020    Movie             517
116          2020  TV Show             436
117          2021    Movie             277
118          2021  TV Show             315

[64 rows x 3 columns]

In [65]:
fig3 = px.line(df3, x='release_year', y='Total Contents', color='type', title='Trend of content produced over the years on Netflix')
fig3.show()

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      8807 non-null   object
 4   cast          8807 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [66]:
df4 = data[['release_year', 'description']]

In [68]:
for index, row in df4.iterrows():
  z = row['description']
  testimonials = TextBlob(z)
  p = testimonials.sentiment.polarity
  if p == 0:
    sent = 'Neutral'
  elif p > 0:
    sent = 'Positive'
  else:
    sent = 'Negative'
  df4.loc[[index,2], 'Sentiment'] = sent

In [69]:
df4.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Sentiment
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,No Cast Specified,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Positive
1,s2,TV Show,Blood & Water,No Director Specified,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",Neutral
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,Negative
3,s4,TV Show,Jailbirds New Orleans,No Director Specified,No Cast Specified,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",Negative
4,s5,TV Show,Kota Factory,No Director Specified,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,Neutral

In [71]:
df5 = df4.groupby(['release_year', 'Sentiment']).size().reset_index(name='Total contents')
df5

     release_year Sentiment  Total contents
0            1925   Neutral               1
1            1942   Neutral               2
2            1943  Negative               1
3            1943   Neutral               2
4            1944  Negative               1
..            ...       ...             ...
180          2020   Neutral             161
181          2020  Positive             519
182          2021  Negative             164
183          2021   Neutral              85
184          2021  Positive             343

[185 rows x 3 columns]

In [72]:
df5 = df5[df5.release_year >= 1990]
df5

     release_year Sentiment  Total contents
89           1990  Negative               8
90           1990   Neutral               2
91           1990  Positive              12
92           1991  Negative               5
93           1991   Neutral               4
..            ...       ...             ...
180          2020   Neutral             161
181          2020  Positive             519
182          2021  Negative             164
183          2021   Neutral              85
184          2021  Positive             343

[96 rows x 3 columns]

In [74]:
fig4 = px.line(df5, x='release_year', y='Total contents', color='Sentiment', title='Sentiment of content on Netflix')
fig4.show()